### ISSUE TITLE
Error occurred prerendering page "/sitemap.xml"

### ISSUE THREAD

**Issue by Vent3st** [steven-tey/precedent#48]
`Error occurred prerendering page "/sitemap.xml". Read more: https://nextjs.org/docs/messages/prerender-error
Error: 
Invalid `prisma.user.findMany()` invocation:
The table `public.User` does not exist in the current database.
    at pn.handleRequestError (/vercel/path0/node_modules/.pnpm/@prisma+client@4.13.0_prisma@4.13.0/node_modules/@prisma/client/runtime/library.js:176:6477)
    at pn.request (/vercel/path0/node_modules/.pnpm/@prisma+client@4.13.0_prisma@4.13.0/node_modules/@prisma/client/runtime/library.js:176:5786)
    at async t._request (/vercel/path0/node_modules/.pnpm/@prisma+client@4.13.0_prisma@4.13.0/node_modules/@prisma/client/runtime/library.js:179:10484)
    at async sitemap (/vercel/path0/.next/server/app/sitemap.xml/route.js:154:19)
    at async GET (/vercel/path0/.next/server/app/sitemap.xml/route.js:183:16)
info  - Generating static pages (5/5)`

**Comment by antcar0929** [comment]
Seems like a duplicate of #46

**Comment by vignesh-gupta** [comment]
run `npx prisma db` push

set pre-build as `next build` in package.json
